language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
- node
script:
- npm run build
- npm run ci
sudo: required
notifications:
  email: false
  slack:
    secure: zLUKdI6mmTeaflFUxySE0ZeRTtsTjsnD/b2hoMrxZ28UdDKj48eKkIG/AbUKdrK4v85e/psldFa6VuKkQ4Y2RuDgIEuuKstScQRpFOjyB3rMde+xbPll7F0v8kVOZt+JTBHtk9Q37MpS/uAzrgoQJs469mQ6S9+7M/3SmXw8GhzXSiQtixiN3vS3ieovZwLfVLnpPGU31zk/s5KVtcwy60dzU/el9GRdcWkzJ2vDxzZIniGzrALSSJPlQvVP6NQ3M2tWtHAqDd4IcGzyr7laQwIdvkGVour2JZdRWocficd/LGCiOAH7HZORWjsHU5gn4nLF4UxAil3EyLsjUZzCvHiRcF5kR0CcuB0pgKXDwEfD8AldrPg+U5k9W3glJn0K7X4ycIyJvBi1TfN5vfSOu2IcOet2pL/PtiTnUXt9ePQvsAhIHnd+py4EgIKgNr6kS4JRW6sUEL8QBM/qffOhcmuM7cOuRgMjPNAEaALVEQ3JeiVvkYMzsGJBskPA6xIEc5OcGMuRN1jCw89wjU6ovQS2BxDZLxAxoGXKIFnT8ieLf3jvZUM/0WRwUxhmyaM/FETG/AZy0a+KUYpG2WXXfa3aVoJmhXz0StiWr9+rAF0qosJQilhHiFNHlI8nAH9idtPiVCeA1vy8KzwF2x8Xeph+L265SGBufzVLMPfFaNs=
deploy:
  provider: npm
  email: sebastian@katallaxie.me
  api_key:
    secure: 3myzFGb1kOyXjPPRdDUR4YosblOc6cDMgVcSkS6cjoq0ji1OrEJYxDEjMlLgFLvfABhnVwwdThBU/zOYkyTsd+GzfyyDkzRzgcZX6mhLOc2mDM8dl3bTtQZB17Mxl1DT2ejgbQse3oKaY4ajYYjqg2QBi0DRwDXfLQaLwH0sRQ0E3HfSyVz2mi4uWmzIaDqfLLWQ+og58XPk76aXlWh68U3n9YwPd0w2wZAOva5ZOMOShRL5ZRFS/sD6ma8lwAOVYmwU2LTzfpGJLiwkLtt8b/H1qPWJknoC08UQSJBgpyDMkFnMIUJ9TGTYNYw8GRRWZXi89agADyEByTjUulwF9xRflLEY/zTwr7RRIQXdu7RjswjRqeSct0Q5T1YlPSBay246FW/YaniOt+zLc/byY4bEBR+ED1I5pa3THf4/3SyQSZDThjSGtJFz2XTOvQTCuXM/22bHwXniQeXJkQWp1Elnzho4bC+gifjrT5Sbb1d1OSQgm1VSnvwLmJDwKtkQMwYiJyYdKxxqqxEhCqMzFvG2VvZBPbKepEZai31o0rglKWytB2j2qm1f7I/S41xfxSaAZJtbda4WQvsHcLfn8G+2odHzsHDQQZfQe+GIp2En0EWdXTp+4salwhncmRcz818iKZP1E28wNhKyD5F2H5FHdedIzb30FaJp9HaIbSc=
  on:
    tags: true
    repo: andersnormal/generator-create-go
